#!/bin/sh

#SBATCH --job-name=BnB_within

#SBATCH --output=BnB.o

#SBATCH --error=BnB.error

#SBATCH --partition=savio

#SBATCH --time=400:00:00

#SBATCH --nodes=2

#SBATCH --ntasks-per-node=1

#SBATCH --cpus-per-task=20

# QoS:

#SBATCH --qos=nuclear_savio_normal

#

# Account:

#SBATCH -A co_nuclear

#SBATCH --mail-user=keckler@berkeley.edu
#SBATCH --mail-type=all

# run command
setenv OMP_NUM_THREAD 20

mpirun -np 2 --map-by ppr:1:node:pe=20 ~/bin/sss2/sss2 -omp 20 BnB
